# coding: utf-8

"""
    Speech to Text API v3.0

    Speech to Text API v3.0.  # noqa: E501

    OpenAPI spec version: v3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class InternalModel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'storage_prefix': 'str',
        '_self': 'str'
    }

    attribute_map = {
        'storage_prefix': 'storagePrefix',
        '_self': 'self'
    }

    def __init__(self, storage_prefix=None, _self=None, _configuration=None):  # noqa: E501
        """InternalModel - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._storage_prefix = None
        self.__self = None
        self.discriminator = None

        if storage_prefix is not None:
            self.storage_prefix = storage_prefix
        if _self is not None:
            self._self = _self

    @property
    def storage_prefix(self):
        """Gets the storage_prefix of this InternalModel.  # noqa: E501


        :return: The storage_prefix of this InternalModel.  # noqa: E501
        :rtype: str
        """
        return self._storage_prefix

    @storage_prefix.setter
    def storage_prefix(self, storage_prefix):
        """Sets the storage_prefix of this InternalModel.


        :param storage_prefix: The storage_prefix of this InternalModel.  # noqa: E501
        :type: str
        """

        self._storage_prefix = storage_prefix

    @property
    def _self(self):
        """Gets the _self of this InternalModel.  # noqa: E501

        The location of this entity.  # noqa: E501

        :return: The _self of this InternalModel.  # noqa: E501
        :rtype: str
        """
        return self.__self

    @_self.setter
    def _self(self, _self):
        """Sets the _self of this InternalModel.

        The location of this entity.  # noqa: E501

        :param _self: The _self of this InternalModel.  # noqa: E501
        :type: str
        """

        self.__self = _self

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InternalModel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InternalModel):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, InternalModel):
            return True

        return self.to_dict() != other.to_dict()
