name: bicep what-if

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} 
          enable-AzPSSession: true

      - name: what-if using Azure CLI
        run: |
          set +e
          results=$(az deployment sub what-if --template-file "./5.internal-document-search/infra/main.bicep" --location JapanEast -p vmLoginPassword=dummy -p resourceGroupName=rg-${{ github.run_id }} -p isPrivateNetworkEnabled=false -p environmentName=${{ github.run_id }} -p location=japaneast 2>&1)
          echo "$results"
          # Check if "Error" is present in $results
          if echo "$results" | grep -i "Error"; then
          echo "Error found in what-if results. Exiting..."
          exit 1
          fi